const EMPTY = [];

const SMALL = [
  {
    id: 1,
    imageSource: "/images/MisoRamen.png",
    title: "Miso Ramen",
    price: 8.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: "/images/shoyuRamen.png",
    title: "Shoyu Ramen",
    price: 8.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  // {
  //   id: 2,
  //   imageSource: "/images/mugicha.png",
  //   title: "mugicha",
  //   price: .556,
  //   quantity: 0,
  //   isAvailable: true,
  //   isAdvertised: false,
  // },
];

const MEDIUM = [
  {
    id: 1,
    imageSource: "/images/MisoRamen.png",
    title: "Miso Ramen",
    price: 8.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: "/images/shoyuRamen.png",
    title: "Shoyu Ramen",
    price: 8.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 3,
    imageSource: "/images/mazesoba.png",
    title: "Mazesoba",
    price: 8.367,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 4,
    imageSource: "/images/ShioRamen.png",
    title: "Shio Ramen",
    price: 8.568,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 5,
    imageSource: "/images/tonkotsuRamen.png",
    title: "Tonkotsu Ramen",
    price: 9.487,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

const LARGE = [
  {
    id: 1,
    imageSource: "/images/MisoRamen.png",
    title: "Miso Ramen",
    price: 8.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: "/images/shoyuRamen.png",
    title: "Shoyu Ramen",
    price: 8.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 3,
    imageSource: "/images/mazesoba.png",
    title: "Mazesoba",
    price: 8.367,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 4,
    imageSource: "/images/ShioRamen.png",
    title: "Shio Ramen",
    price: 8.568,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 5,
    imageSource: "/images/tonkotsuRamen.png",
    title: "Tonkotsu Ramen",
    price: 9.487,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 6,
    imageSource: "/images/tsukemen.png",
    title: "Tsukemen",
    price: 10.356,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 7,
    imageSource: "/images/coke.png",
    title: "Coca-Cola 33cl",
    price: 2.867,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 8,
    imageSource: "/images/mugicha.png",
    title: "Mugicha 33cl",
    price: 3.1678,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 9,
    imageSource: "/images/ramune.png",
    title: "Ramune 33cl",
    price: 3.7,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 10,
    imageSource: "/images/bubbletea.png",
    title: "Bubble Tea 75cl",
    price: 4.678,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

export const fakeMenu = {
  EMPTY,
  SMALL,
  MEDIUM,
  LARGE,
};
